# *********************
# >FileName: tmux.conf
# >Author: KnightCS
# >Note: This file is the tmux config file.
# *********************

# *********************
# * This part is shortcut set.

# change the default delay to make it more responsive
set-option -sg escape-time 50

# use vim key bindings
set-window-option -g mode-keys vi
set-window-option -g status-keys vi

# set bell
set-option -gq bell-action none
set-option -gq bell-on-alert off

set-option -g mouse on

# start window & pane index at 1
set-option -g base-index 1
set-window-option -g pane-base-index 1

# don't rename windows automatically
set-option -g allow-rename off
set-option -g renumber-windows on
set-window-option -g aggressive-resize on

# enable event notification
set-window-option -g monitor-activity on
set-option -g visual-activity on

# clock
set-window-option -g clock-mode-style 24

set-option -g default-terminal "xterm-256color"
set-option -as terminal-overrides ",xterm-256color:Tc"

source-file "$HOME/.config/tmux/theme.tmux"
source-file "$HOME/.config/tmux/key.tmux"
source-file "$HOME/.config/tmux/hook.tmux"
source-file "$HOME/.config/tmux/tpm.tmux"

run-shell 'bash "$HOME/.config/tmux/tmux.sh"'
